# -----------------------------
# Material Theme Configuration
# ------------------------------
# red, pink, purple, deep purple, indigo, 
# blue, light blue, cyan, teal, green, light green, 
# lime, yellow, amber, orange, deep orange, brown, 
# grey, blue grey , black, white
#    primary: pink # teal
#    accent: indigo
#
# *** FONT ***
# Guide: https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=fonts
# Google Fonts Supported: https://fonts.google.com/
#
# *** BLOG ***
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
# ---------------------------------

# Project information
site_name: Prompty Workshop
site_url: https://nitya.github.io/codespaces-prompty
site_author: Nitya Narasimhan
site_description: >-
  Exploring Prompty usage one code-first tutorial at a time

# Repository
repo_name: nitya/codespaces-prompty
repo_url: https://github.com/nitya/odespaces-prompty

# Copyright
copyright: Copyright &copy; 2024 - present Microsoft

# Configuration
site_name: "Prompty Workshop"
theme:
  name: material

  font:
    code: Roboto Mono #Monospaced
    text: Roboto #Regular

  logo: img/prompty.svg

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

  features:

# Configure Plugins
plugins:

# Configure Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
    